version: "3.8"
services:
  app:
    build:
      args:
        user: william
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: recibo
    container_name: recibo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - recibo

  db:
    image: mysql:5.7
    container_name: recibo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - recibo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name:  recibo_phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    restart: always
    networks:
      - recibo
    ports:
      - "9001:80"

  nginx:
    image: nginx:alpine
    container_name: recibo-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - recibo

networks:
  recibo:
    driver: bridge